In [18]:
import numpy as np
stock_change=np.random.normal(loc=2,scale=0.7,size=(8,10))
stock_change[0][0:3]


array([3.10850979, 2.53645163, 2.64460722])

In [80]:
# 一、
# a.modify shape:reshape;resize;T
# 1.return new array ,but original array doesn't change
stock_change.reshape(10,8)
print()

In [ ]:
# 2.not return,change original array 
stock_change.resize((10,8))

In [26]:
# 3.reverse row and column
# stock_change.T

In [81]:
# b.modify type
# astype
stock_change.astype('int32')
# tostring:serialization(ˌsɪəriəlaɪˈzeɪʃn)
# stock_change.tostring()

array([[3, 2, 2, 2, 1, 2, 1, 1, 2, 2],
       [1, 1, 2, 2, 3, 3, 1, 0, 2, 3],
       [2, 1, 1, 1, 1, 1, 1, 2, 2, 3],
       [2, 3, 3, 2, 2, 1, 2, 2, 2, 1],
       [2, 0, 1, 1, 1, 1, 1, 1, 3, 0],
       [1, 0, 1, 1, 1, 1, 2, 1, 1, 3],
       [1, 2, 3, 2, 2, 1, 2, 1, 2, 2],
       [2, 1, 1, 0, 2, 1, 2, 2, 1, 0]])

In [48]:
# c.Remove Duplicates
nparray5=np.array([[1,2,3],
                   [2,5,3]])

np.unique(nparray5)

array([1, 2, 3, 5])

In [54]:
# 二、operation
# a.logic operation
# generate a array
import random 
# *normal distribution
# loc is average value,scale is standard deviation
nparray6=np.random.normal(loc=1,scale=0.4,size=(7,8))
# 1.return a boole array
nparray6>0.5
# logical_and:&
np.logical_and(nparray6>0,nparray6<1)

# 2.boole index
nparray6[nparray6>0.5]
# 3.all() :equivalently operation &(and)
# any() :equivalently operation ||(or)
# return true when all is true
np.all(nparray6>0.5)
# 4.ternary operator:where
np.where(nparray6>0,1,0)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [58]:
# b.static operation,min max,median,var(variance),std(standard deviation)),mean(mean value)
# *normal distribution
# loc is average value,scale is standard deviation
nparray7=np.random.normal(loc=1,scale=0.4,size=(7,8))
# get max in row
nparray7.max(axis=1)
# get max in column
nparray7.max(axis=0)
# get the index of max in column
nparray7.argmax(axis=0)

array([1.64158059, 1.50431301, 1.56408546, 2.06660554, 1.56823976,
       1.85144506, 1.62981449, 1.48379883])

In [79]:
# c.operation in array
# 1.operation in array and number
nparray8=np.random.uniform(low=0,high=10,size=(3,3))
nparray9=np.random.uniform(low=10,high=20,size=(3,3))
npa10=nparray8.astype('int32')
npa11=nparray9.astype('int32')
npa10+=10
# 1.operation in array and array
npa10+npa11

array([[35, 28, 29],
       [20, 33, 26],
       [28, 27, 28]])

In [89]:
# c.operation in matrix
nparray12=np.random.uniform(low=1,high=20,size=(3,2))
nparray13=np.random.uniform(low=1,high=20,size=(2,3))

data_mat1=np.mat(nparray12)
data_mat2=np.mat(nparray13)
# matric multiplication :three ways
np.matmul(data_mat1,data_mat2)#array is also ok
np.dot(data_mat1,data_mat2)#array is also ok
data_mat1*data_mat2


matrix([[359.1112087 , 261.78457403, 161.12202978],
        [355.14736774, 237.49400977, 148.5525683 ],
        [100.68102775,  73.7316041 ,  45.34249021]])

matrix([[14.01606688,  1.00268513,  8.81280669],
        [ 5.7733511 , 10.19534419,  3.75925193],
        [10.69648359,  1.98631229, 16.9445338 ]])